// GENERATED by scripts/frostbyte-art/trace.mjs: every traced backdrop, keyed by mapAsset.
import * as caverns from './room-caverns.js';
import * as court from './room-court.js';
import * as docksAway from './room-docks-away.js';
import * as docksPort from './room-docks-port.js';
import * as lighthouseGallery from './room-lighthouse-gallery.js';
import * as lighthouseRest from './room-lighthouse-rest.js';
import * as moonwell from './room-moonwell.js';
import * as plaza from './room-plaza.js';
import * as trail from './room-trail.js';
import * as whisperpine from './room-whisperpine.js';

export const TRACED_ART = {
  'room-caverns': caverns,
  'room-court': court,
  'room-docks-away': docksAway,
  'room-docks-port': docksPort,
  'room-lighthouse-gallery': lighthouseGallery,
  'room-lighthouse-rest': lighthouseRest,
  'room-moonwell': moonwell,
  'room-plaza': plaza,
  'room-trail': trail,
  'room-whisperpine': whisperpine,
};
