// GENERATED by scripts/frostbyte-art/trace.mjs from assets/room-petshop.jpg. Do not hand-edit:
// change scripts/frostbyte-art/rooms.mjs and re-run `node scripts/frostbyte-art/trace.mjs room-petshop`.
// GROUND: the painted walkable ground. HOLES: painted things standing in it (props block only at
// their footprint). OCCLUDERS: [x, y, w, h, z] cut-outs of assets/occluders/room-petshop.png drawn over
// anyone whose feet are above z (behind the prop).
export const GROUND = [
  [442, 392], [1198, 423], [1198, 445], [1120, 445], [1130, 606], [1230, 815], [1361, 811], [1363, 818], [1231,
  880], [952, 900], [945, 960], [590, 960], [573, 885], [284, 880], [238, 863], [236, 856], [244, 854], [305,
  870], [465, 651], [455, 515], [360, 497], [362, 490], [445, 475],
];

export const HOLES = [

];

export const OCCLUDERS = [

];
