// content/curios.js — world discovery registry. Entries land with their room phase, at which point
// ids and labels are shipped content contracts.
export const CURIO_REGISTRY = Object.freeze([
  Object.freeze({ id: 'court-window-wave', roomId: 'court', label: 'The Courteous Display' }),
  Object.freeze({ id: 'court-fountain-glimmer', roomId: 'court', label: 'Coin Beneath the Ice' }),
  Object.freeze({ id: 'court-wind-chimes', roomId: 'court', label: 'Bluehour Ice Chimes' }),
  Object.freeze({ id: 'court-awning-snow', roomId: 'court', label: 'The Sudden Snowcap' }),
  Object.freeze({ id: 'court-kettle-steam', roomId: 'court', label: 'Overtime Kettle' }),
  Object.freeze({ id: 'court-postbox-rattle', roomId: 'court', label: 'The Talkative Postbox' }),
  Object.freeze({ id: 'workshop-bellows-puff', roomId: 'workshop', label: 'The Sighing Bellows' }),
  Object.freeze({ id: 'workshop-gizmo-chain', roomId: 'workshop', label: 'Seven-Step Contraption' }),
  Object.freeze({ id: 'workshop-tube-thunk', roomId: 'workshop', label: 'Pneumatic Post' }),
  Object.freeze({ id: 'workshop-blueprint-cycle', roomId: 'workshop', label: 'Plans for Possible Things' }),
  Object.freeze({ id: 'workshop-snowputer', roomId: 'workshop', label: 'Snowputer Prototype' }),
  Object.freeze({ id: 'docks-tidepool-duck', roomId: 'docks', label: 'Tidepool Vanishing Act' }),
  Object.freeze({ id: 'docks-bottle-post', roomId: 'docks', label: 'Bottle Post Dispatch' }),
  Object.freeze({ id: 'docks-harbor-bell', roomId: 'docks', label: 'Bell Across the Floes' }),
  Object.freeze({ id: 'docks-crane-swing', roomId: 'docks', label: 'The Patient Crane' }),
  Object.freeze({ id: 'docks-buoy-bob', roomId: 'docks', label: 'Outer Marker Nod' }),
  Object.freeze({ id: 'docks-gull-scatter', roomId: 'docks', label: 'Whitewing Commotion' }),
  Object.freeze({ id: 'docks-underpier-cache', roomId: 'docks', label: 'Ledge Below the Pier' }),
  Object.freeze({ id: 'lighthouse-rest-stove-sigh', roomId: 'lighthouse-rest', label: 'Cedar Stove Sigh' }),
  Object.freeze({ id: 'lighthouse-rest-kettle-tick', roomId: 'lighthouse-rest', label: 'Three Patient Ticks' }),
  Object.freeze({ id: 'lighthouse-rest-cot-quilt', roomId: 'lighthouse-rest', label: 'Currents in the Quilt' }),
  Object.freeze({ id: 'lighthouse-rest-stair-answer', roomId: 'lighthouse-rest', label: 'One Turn Later' }),
  Object.freeze({ id: 'lighthouse-gallery-lamp-prism', roomId: 'lighthouse-gallery', label: 'Pocket Sunrise' }),
  Object.freeze({ id: 'lighthouse-gallery-pennant', roomId: 'lighthouse-gallery', label: 'The Unfelt Wind' }),
  Object.freeze({ id: 'lighthouse-gallery-rail-crystals', roomId: 'lighthouse-gallery', label: 'Glass-Step Chime' }),
  Object.freeze({ id: 'lighthouse-gallery-wind-carving', roomId: 'lighthouse-gallery', label: 'Three Notes in the Rail' }),
]);
