// main.js — KAPLAY "Dev District" portfolio. Pixel-art assets generated by gen-assets.js.
// KAPLAY is vendored locally (DOMINIKOS-PLAN §8.1) so offline/preload works — no CDN import.
import kaplay from "./vendor/kaplay.mjs";
import { hotspots, content, INTRO_HINT, TOTAL } from "./content.js";

// ?embedded=1 → running inside a DominikOS window (§8.1): the OS chrome provides close/back,
// so the "← Classic site" escape link is hidden (its href="../" would break out of the OS).
const embedded = new URLSearchParams(location.search).get("embedded") === "1";
if (embedded) {
  const backLink = document.getElementById("back-link");
  if (backLink) backLink.hidden = true;
}

/* ------------------------------------------------------------------ *
 * Engine
 * ------------------------------------------------------------------ */
const k = kaplay({
  global: false,
  touchToMouse: true,
  canvas: document.getElementById("game"),
  pixelDensity: Math.min(window.devicePixelRatio || 1, 2),
  crisp: true,                 // keep pixel art sharp
  background: [40, 56, 38],
  debug: false,
});

// DominikOS pause contract (plan §8.1) — uses KAPLAY's documented pause, not an rAF monkey-patch.
// KAPLAY 3001 pauses via the root game object; debug.paused is the fallback handle.
window.__osBridge?.onReady({
  pause:  () => { k.getTreeRoot ? (k.getTreeRoot().paused = true)  : (k.debug.paused = true);  k.audioCtx?.suspend?.(); },
  resume: () => { k.getTreeRoot ? (k.getTreeRoot().paused = false) : (k.debug.paused = false); k.audioCtx?.resume?.(); },
  setMute: (b) => { k.setVolume?.(b ? 0 : 1); },
});

const SCALE = 3;               // map tile 16px -> 48 world px
const SPEED = 250;
const INTERACT_R = 168;
// road spans world y 336..480; let the player roam the full width of the road
const BOUNDS = { x0: 24, x1: 3048, y0: 340, y1: 600 };

// native pixel heights (must match gen-assets.js building sizes)
const BUILD_H = { ou: 54, norbert: 46, rubicall: 58, welcominn: 60, deloitte: 80, projects: 56 };
const PROP_H = { sign: 22, board: 16, mailbox: 18, portal: 26 };
const spriteKey = (h) => (h.kind === "building" ? `build_${h.id}` :
  h.kind === "sign" ? "signpost" : h.kind === "board" ? "corkboard" : h.kind);
const nativeH = (h) => (h.kind === "building" ? BUILD_H[h.id] : PROP_H[h.kind]);

/* ------------------------------------------------------------------ *
 * Asset loading
 * ------------------------------------------------------------------ */
k.loadSprite("map", "./assets/map.png");
k.loadSprite("hero", "./assets/character.png", {
  sliceX: 4, sliceY: 3,
  anims: {
    "idle-down": 0, "walk-down": { from: 0, to: 3, loop: true, speed: 8 },
    "idle-side": 4, "walk-side": { from: 4, to: 7, loop: true, speed: 8 },
    "idle-up": 8, "walk-up": { from: 8, to: 11, loop: true, speed: 8 },
  },
});
for (const id of Object.keys(BUILD_H)) k.loadSprite(`build_${id}`, `./assets/build_${id}.png`);
k.loadSprite("signpost", "./assets/signpost.png");
k.loadSprite("corkboard", "./assets/corkboard.png");
k.loadSprite("mailbox", "./assets/mailbox.png");
k.loadSprite("portal", "./assets/portal.png");

/* ------------------------------------------------------------------ *
 * DOM hooks
 * ------------------------------------------------------------------ */
const el = (id) => document.getElementById(id);
const hud = { hint: el("hud-hint"), progress: el("hud-progress"), interactBtn: el("interact-btn") };
const dlg = {
  overlay: el("dialogue-overlay"), title: el("dialogue-title"), subtitle: el("dialogue-subtitle"),
  body: el("dialogue-body"), prev: el("dialogue-prev"), next: el("dialogue-next"),
  pager: el("dialogue-pager"), close: el("dialogue-close"),
};
const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const visited = new Set();

/* ------------------------------------------------------------------ *
 * Dialogue overlay controller (HTML)
 * ------------------------------------------------------------------ */
let dlgState = null;
const dialogueOpen = () => dlgState !== null;

function updateProgress() {
  hud.progress.textContent = `Discovered ${visited.size} / ${TOTAL}`;
  hud.progress.classList.toggle("complete", visited.size === TOTAL);
}
function typeHtml(container, html, done) {
  container.innerHTML = html;
  if (reduceMotion) { done && done(); return () => {}; }
  const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT);
  const nodes = []; let n;
  while ((n = walker.nextNode())) { nodes.push({ n, full: n.nodeValue }); n.nodeValue = ""; }
  let ni = 0, ci = 0;
  const timer = setInterval(() => {
    if (ni >= nodes.length) { clearInterval(timer); done && done(); return; }
    const cur = nodes[ni]; ci += 1; cur.n.nodeValue = cur.full.slice(0, ci);
    if (ci >= cur.full.length) { ni += 1; ci = 0; }
  }, 10);
  return () => { clearInterval(timer); nodes.forEach((x) => { x.n.nodeValue = x.full; }); done && done(); };
}
function renderPage() {
  const pages = content[dlgState.id].pages, total = pages.length;
  dlgState.typing = true;
  dlgState.skip = typeHtml(dlg.body, pages[dlgState.page].html, () => { dlgState.typing = false; });
  dlg.prev.hidden = !(total > 1 && dlgState.page > 0);
  dlg.next.hidden = !(total > 1 && dlgState.page < total - 1);
  dlg.pager.textContent = total > 1 ? `${dlgState.page + 1} / ${total}` : "";
}
function openDialogue(id) {
  const entry = content[id]; if (!entry) return;
  dlgState = { id, page: 0, skip: null, typing: false };
  visited.add(id); updateProgress();
  document.body.classList.add("has-interacted");
  dlg.title.textContent = entry.title || "";
  dlg.subtitle.textContent = entry.subtitle || ""; dlg.subtitle.hidden = !entry.subtitle;
  dlg.overlay.classList.remove("hidden");
  renderPage(); dlg.close.focus();
}
function advance() {
  if (!dlgState) return;
  if (dlgState.typing && dlgState.skip) { dlgState.skip(); return; }
  const total = content[dlgState.id].pages.length;
  if (dlgState.page < total - 1) { dlgState.page += 1; renderPage(); } else closeDialogue();
}
function pageBack() { if (dlgState && dlgState.page > 0) { dlgState.page -= 1; renderPage(); } }
function closeDialogue() {
  if (dlgState && dlgState.skip) dlgState.skip();
  dlgState = null; dlg.overlay.classList.add("hidden"); dlg.body.innerHTML = "";
}
dlg.close.addEventListener("click", closeDialogue);
dlg.next.addEventListener("click", advance);
dlg.prev.addEventListener("click", pageBack);
dlg.body.addEventListener("click", advance);
dlg.overlay.addEventListener("mousedown", (e) => { if (e.target === dlg.overlay) closeDialogue(); });
window.addEventListener("keydown", (e) => {
  if (!dialogueOpen()) return;
  if (e.key === "Escape") { closeDialogue(); e.preventDefault(); }
  else if (e.key === "Enter" || e.key === "ArrowRight") { advance(); e.preventDefault(); }
  else if (e.key === "ArrowLeft") { pageBack(); e.preventDefault(); }
});

/* ------------------------------------------------------------------ *
 * Scene
 * ------------------------------------------------------------------ */
k.scene("main", () => {
  k.add([k.sprite("map"), k.pos(0, 0), k.scale(SCALE), k.z(-1000)]);

  // hotspots
  const built = [];
  for (const h of hotspots) {
    const wH = nativeH(h) * SCALE;
    const obj = k.add([
      k.sprite(spriteKey(h)), k.pos(h.x, h.y), k.anchor("bot"), k.scale(SCALE),
      k.area(), k.z(h.y), { hsId: h.id, baseY: h.y, worldH: wH },
    ]);
    if (h.id === "deloitte")
      k.add([k.text("★", { size: 22 }), k.pos(h.x, h.y - wH - 6), k.anchor("center"),
             k.color(k.Color.fromHex("#ffd84d")), k.z(100000)]);

    // floating label
    const topY = h.y - wH - 16;
    const lw = Math.max(46, h.label.length * 8 + 14);
    k.add([k.rect(lw, 20, { radius: 4 }), k.pos(h.x, topY), k.anchor("center"),
           k.color(k.Color.fromHex("#0d0e15")), k.opacity(0.8), k.z(100000)]);
    k.add([k.text(h.label, { size: 12 }), k.pos(h.x, topY), k.anchor("center"),
           k.color(k.Color.fromHex("#f4f4f8")), k.z(100001)]);
    built.push(obj);
  }

  // active-hotspot prompt
  const prompt = k.add([
    k.text("▼ press E", { size: 14 }), k.pos(0, 0), k.anchor("center"),
    k.color(k.Color.fromHex("#ffcf6b")), k.opacity(0), k.z(100002),
  ]);

  // player
  const player = k.add([
    k.sprite("hero", { anim: "idle-down" }), k.pos(150, 408), k.anchor("bot"),
    k.scale(SCALE), k.z(408), { dir: "down" },
  ]);

  // camera
  function fitCam() { const r = k.width() / k.height(); k.setCamScale(k.vec2(r < 1 ? 0.85 : 1.15)); }
  fitCam(); k.onResize(fitCam);

  // interaction state
  let moveTarget = null;
  let active = null;
  const interact = () => { if (active && !dialogueOpen()) openDialogue(active.hsId); };
  k.onKeyPress("e", interact);
  k.onKeyPress("space", interact);
  hud.interactBtn.addEventListener("click", interact);

  // mouse/touch: click the object you're standing at to read it; otherwise walk toward the point
  k.onMousePress(() => {
    if (dialogueOpen()) return;
    const hov = built.find((b) => b.isHovering());
    if (hov && hov === active) { openDialogue(hov.hsId); return; }
    moveTarget = k.toWorld(k.mousePos());
  });

  // animation helper (only re-play on change)
  let curAnim = "idle-down";
  function setAnim(name, flip) {
    player.flipX = !!flip;
    if (curAnim !== name) { curAnim = name; player.play(name); }
  }

  k.onUpdate(() => {
    const frozen = dialogueOpen();
    const prevX = player.pos.x, prevY = player.pos.y;
    let dx = 0, dy = 0;
    if (!frozen) {
      if (k.isKeyDown("left") || k.isKeyDown("a")) dx -= 1;
      if (k.isKeyDown("right") || k.isKeyDown("d")) dx += 1;
      if (k.isKeyDown("up") || k.isKeyDown("w")) dy -= 1;
      if (k.isKeyDown("down") || k.isKeyDown("s")) dy += 1;
    }
    let intend = false;
    if (dx || dy) {
      moveTarget = null;
      const len = Math.hypot(dx, dy);
      player.move((dx / len) * SPEED, (dy / len) * SPEED);
      intend = true;
    } else if (moveTarget && !frozen) {
      const to = moveTarget.sub(player.pos);
      if (to.len() > 6) { const v = to.unit(); dx = v.x; dy = v.y; player.move(v.x * SPEED, v.y * SPEED); intend = true; }
      else moveTarget = null;
    }

    // clamp to the road; if we were blocked at an edge, stop (don't moon-walk in place)
    player.pos.x = Math.max(BOUNDS.x0, Math.min(BOUNDS.x1, player.pos.x));
    player.pos.y = Math.max(BOUNDS.y0, Math.min(BOUNDS.y1, player.pos.y));
    const moved = Math.hypot(player.pos.x - prevX, player.pos.y - prevY) > 0.4;
    if (intend && !moved) moveTarget = null;

    // face the intended direction even when blocked; animate only while actually moving
    if (dx || dy) {
      if (Math.abs(dy) >= Math.abs(dx)) player.dir = dy < 0 ? "up" : "down";
      else player.dir = dx < 0 ? "left" : "right";
    }
    if (intend && moved) {
      if (player.dir === "up") setAnim("walk-up", false);
      else if (player.dir === "down") setAnim("walk-down", false);
      else setAnim("walk-side", player.dir === "left");
    } else {
      const idle = player.dir === "left" || player.dir === "right" ? "idle-side" : `idle-${player.dir}`;
      setAnim(idle, player.dir === "left");
    }
    player.z = player.pos.y;

    k.setCamPos(player.pos.x, player.pos.y - 50);

    // nearest interactable
    let best = null, bestD = INTERACT_R;
    for (const b of built) {
      const d = Math.hypot(b.pos.x - player.pos.x, b.baseY - player.pos.y);
      if (d < bestD) { bestD = d; best = b; }
    }
    if (best !== active) {
      active = best;
      for (const b of built) b.scale = k.vec2(b === active ? SCALE * 1.07 : SCALE);
    }
    if (active && !frozen) {
      hud.interactBtn.textContent = `▶ View ${labelFor(active.hsId)}`;
      hud.interactBtn.classList.add("show");
      prompt.pos = k.vec2(active.pos.x, active.baseY - active.worldH - 34);
      prompt.opacity = 0.55 + 0.45 * Math.abs(Math.sin(k.time() * 4));
    } else {
      hud.interactBtn.classList.remove("show");
      prompt.opacity = 0;
    }
  });
});

function labelFor(id) {
  const h = hotspots.find((x) => x.id === id);
  return (h ? h.label : "").replace(" →", "").replace(" ★", "");
}

/* ------------------------------------------------------------------ *
 * Boot
 * ------------------------------------------------------------------ */
hud.hint.textContent = INTRO_HINT;
updateProgress();
k.go("main");
